version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: star
      POSTGRES_PASSWORD: star
      POSTGRES_DB: star
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
