"""jajaj planet

Revision ID: 21c0bb29142b
Revises: 7b3196d8fc41
Create Date: 2023-11-26 21:02:23.955300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c0bb29142b'
down_revision = '7b3196d8fc41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('planet_star_id_fkey', 'planet', type_='foreignkey')
    op.create_foreign_key(None, 'planet', 'star', ['star_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.create_foreign_key('planet_star_id_fkey', 'planet', 'star', ['star_id'], ['id'])
    # ### end Alembic commands ###
