"""jajaj planet

Revision ID: 24ff71cb3449
Revises: 21c0bb29142b
Create Date: 2023-11-26 21:02:28.081729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ff71cb3449'
down_revision = '21c0bb29142b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
