"""populate star_constellation

Revision ID: 295783a6c87c
Revises: 2ffa8f9ffc53
Create Date: 2023-04-08 14:37:26.239480

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '295783a6c87c'
down_revision = '2ffa8f9ffc53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
INSERT INTO star_constellation (star_id, constellation_id)
VALUES
('cc98dce8-afec-4d5c-b027-3a3a3a3a3a3a'::uuid, 'c32b81a9-83a2-40cf-97fc-bcbecc223ee7'::uuid),
('f6a51829-9e2f-4c5f-a1c7-7115d8bda7fc'::uuid, 'c32b81a9-83a2-40cf-97fc-bcbecc223ee7'::uuid),
('c54ba042-0c11-4b0e-9d9b-c5f5c5b5d86c'::uuid, 'c32b81a9-83a2-40cf-97fc-bcbecc223ee7'::uuid),
('76a2a29a-af8c-4617-bb57-0d79b1319d04'::uuid, 'c32b81a9-83a2-40cf-97fc-bcbecc223ee7'::uuid),
('af14baab-2e2b-4a12-a9f9-007aa0a0e64e'::uuid, 'd4a81c3b-d481-4e0d-a8d5-7c987b2e9f02'::uuid),
('cc98dce8-afec-4d5c-b027-3a3a3a3a3a3a'::uuid, '84b94c48-f9af-43db-b2a2-b7d50be72de5'::uuid),
('c54ba042-0c11-4b0e-9d9b-c5f5c5b5d86c'::uuid, '84b94c48-f9af-43db-b2a2-b7d50be72de5'::uuid);
    '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
