"""rm change-row column

Revision ID: 2ebd4c5386f3
Revises: 4d937cbf9e4b
Create Date: 2023-12-01 14:27:43.325371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebd4c5386f3'
down_revision = '4d937cbf9e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'column_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('column_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
