"""populate planets

Revision ID: 2ffa8f9ffc53
Revises: eae5d300641d
Create Date: 2023-04-08 14:32:51.151023

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2ffa8f9ffc53'
down_revision = 'eae5d300641d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
INSERT INTO planet (id, name, mass, diameter, distance_from_star, orbital_period, surface_temperature, star_id)
VALUES
('1d4cc4af-4c08-4283-aa18-74b48a2b19c3'::uuid, 'Mercury', 0.330, 4879, 0.39, '87.97 days'::interval, 340, 'cc98dce8-afec-4d5c-b027-3a3a3a3a3a3a'::uuid),
('68ef44cf-dc0e-44a4-9d84-d023768787a4'::uuid, 'Venus', 4.87, 12104, 0.72, '224.7 days'::interval, 737, 'cc98dce8-afec-4d5c-b027-3a3a3a3a3a3a'::uuid),
('d9e9e1d1-003c-49ec-a619-4f29a372aeb6'::uuid, 'Earth', 5.97, 12756, 1.00, '365.25 days'::interval, 288, 'cc98dce8-afec-4d5c-b027-3a3a3a3a3a3a'::uuid),
('7a8d5c5a-05c3-40b2-8d01-b6c853ed07aa'::uuid, 'Mars', 0.642, 6792, 1.52, '1.88 years'::interval, -63, 'cc98dce8-afec-4d5c-b027-3a3a3a3a3a3a'::uuid),
('05886f56-c95e-4063-a7e3-ae3dc1a7f3bb'::uuid, 'Proxima Centauri b', 0.003, 11385, 0.0485, '11.2 days'::interval, -39, 'f6a51829-9e2f-4c5f-a1c7-7115d8bda7fc'::uuid),
('2c5c1e29-4cf0-4f01-88a4-7284e9b3fbcd'::uuid, 'Alpha Centauri Bb', 1.133, 15000, 0.04, '3.24 days'::interval, 1500, '76a2a29a-af8c-4617-bb57-0d79b1319d04'::uuid),
('d82f43c3-3d90-4017-a1e3-0570a9d2f848'::uuid, 'Tartarus', 0.007, 2453, 0.23, '0.39 years'::interval, 1273, 'c54ba042-0c11-4b0e-9d9b-c5f5c5b5d86c'::uuid);
    '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
DELETE FROM planet 
WHERE id IN ('1d4cc4af-4c08-4283-aa18-74b48a2b19c3', '68ef44cf-dc0e-44a4-9d84-d023768787a4', 'd9e9e1d1-003c-49ec-a619-4f29a372aeb6', '7a8d5c5a-05c3-40b2-8d01-b6c853ed07aa', '05886f56-c95e-4063-a7e3-ae3dc1a7f3bb');
    '''
    )
    # ### end Alembic commands ###
