"""add, ondelete=CASCADE

Revision ID: 61103f0e739e
Revises: 619a6785b51d
Create Date: 2023-11-30 16:34:55.718757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61103f0e739e'
down_revision = '619a6785b51d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('constellation_galaxy_id_fkey', 'constellation', type_='foreignkey')
    op.create_foreign_key(None, 'constellation', 'galaxy', ['galaxy_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('star_galaxy_id_fkey', 'star', type_='foreignkey')
    op.create_foreign_key(None, 'star', 'galaxy', ['galaxy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'star', type_='foreignkey')
    op.create_foreign_key('star_galaxy_id_fkey', 'star', 'galaxy', ['galaxy_id'], ['id'])
    op.drop_constraint(None, 'constellation', type_='foreignkey')
    op.create_foreign_key('constellation_galaxy_id_fkey', 'constellation', 'galaxy', ['galaxy_id'], ['id'])
    # ### end Alembic commands ###
