"""rm timefield

Revision ID: 619a6785b51d
Revises: 8c72f08b907f
Create Date: 2023-11-30 13:51:47.184088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "619a6785b51d"
down_revision = "8c72f08b907f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("planet", "orbital_period")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "planet",
        sa.Column(
            "orbital_period", postgresql.TIME(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
