"""add audit table

Revision ID: 68bd91677569
Revises: 61103f0e739e
Create Date: 2023-12-01 14:11:58.877918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68bd91677569"
down_revision = "61103f0e739e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=256), nullable=False),
        sa.Column("column_name", sa.String(length=256), nullable=True),
        sa.Column("row_id", sa.UUID(), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("operation_type", sa.String(length=10), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit")
    # ### end Alembic commands ###
