"""jajaj galaxy

Revision ID: 8c72f08b907f
Revises: 24ff71cb3449
Create Date: 2023-11-26 21:18:08.318590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c72f08b907f'
down_revision = '24ff71cb3449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('galaxy_universe_id_fkey', 'galaxy', type_='foreignkey')
    op.create_foreign_key(None, 'galaxy', 'universe', ['universe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'galaxy', type_='foreignkey')
    op.create_foreign_key('galaxy_universe_id_fkey', 'galaxy', 'universe', ['universe_id'], ['id'])
    # ### end Alembic commands ###
