"""empty message

Revision ID: 90eed17af1b5
Revises: 
Create Date: 2023-03-25 15:42:41.461244

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90eed17af1b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'universe',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('size', sa.Float(), nullable=False),
        sa.Column('composition', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'galaxy',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('universe_id', sa.UUID(), nullable=True),
        sa.Column('size', sa.Float(), nullable=False),
        sa.Column('shape', sa.String(length=50), nullable=True),
        sa.Column('composition', sa.Text(), nullable=True),
        sa.Column('distance_from_earth', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['universe_id'],
            ['universe.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'constellation',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('galaxy_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('shape', sa.String(length=50), nullable=True),
        sa.Column('abbreviation', sa.String(length=50), nullable=True),
        sa.Column('history', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['galaxy_id'],
            ['galaxy.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'star',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('galaxy_id', sa.UUID(), nullable=True),
        sa.Column('spectral_type', sa.String(length=50), nullable=False),
        sa.Column('luminosity', sa.Float(), nullable=False),
        sa.Column('distance_from_earth', sa.Float(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['galaxy_id'],
            ['galaxy.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'planet',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('mass', sa.Float(), nullable=False),
        sa.Column('diameter', sa.Float(), nullable=False),
        sa.Column('distance_from_star', sa.Float(), nullable=False),
        sa.Column('orbital_period', sa.Time(), nullable=True),
        sa.Column('surface_temperature', sa.Float(), nullable=True),
        sa.Column('star_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ['star_id'],
            ['star.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'star_constellation',
        sa.Column('star_id', sa.UUID(), nullable=False),
        sa.Column('constellation_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['constellation_id'],
            ['constellation.id'],
        ),
        sa.ForeignKeyConstraint(
            ['star_id'],
            ['star.id'],
        ),
        sa.PrimaryKeyConstraint('star_id', 'constellation_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star_constellation')
    op.drop_table('planet')
    op.drop_table('star')
    op.drop_table('constellation')
    op.drop_table('galaxy')
    op.drop_table('universe')
    # ### end Alembic commands ###
