"""add new data

Revision ID: c87b3b2d480e
Revises: 2ebd4c5386f3
Create Date: 2023-12-02 13:56:09.438657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c87b3b2d480e"
down_revision = "2ebd4c5386f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
INSERT INTO universe (id, name, size, composition)
VALUES 
('babd88ed-897e-4247-ab2b-c0788910c1fc', 'Наша вселенная', 93000000000, 'Звёзды, галактики, тёмная материя, тёмная энергия');

INSERT INTO galaxy (id, name, universe_id, size, shape, composition, distance_from_earth)
VALUES 
('f84404e6-12be-48e4-b5e3-6ceb366b0c9b', 'Андромеда', 'babd88ed-897e-4247-ab2b-c0788910c1fc', 220000, 'Спиральная', 'Звёзды, пылевые облака, тёмная материя', 2537000),
('511dc56e-973e-487d-a423-0f2632893821', 'Млечный Путь', 'babd88ed-897e-4247-ab2b-c0788910c1fc', 100000, 'Спиральная с перемычкой', 'Звёзды, пылевые облака, тёмная материя', 0),
('a95a89c9-b07b-45d8-81e8-2f1977940b7e', 'Треугольник', 'babd88ed-897e-4247-ab2b-c0788910c1fc', 60000, 'Спиральная', 'Звёзды, пылевые облака, тёмная материя', 2730000),
('6739f02d-ce9e-4ffd-ab36-271dfbe3b859', 'Водоворот', 'babd88ed-897e-4247-ab2b-c0788910c1fc', 60000, 'Спиральная', 'Звёзды, пылевые облака, тёмная материя', 23000000),
('0d9a5365-54af-4689-9529-bfa9dc761d60', 'Сомбреро', 'babd88ed-897e-4247-ab2b-c0788910c1fc', 50000, 'Спиральная с перемычкой', 'Звёзды, пылевые облака, тёмная материя', 29300000);

INSERT INTO star (id, name, galaxy_id, spectral_type, luminosity, distance_from_earth, temperature)
VALUES 
('b3d784c1-1f31-475d-9059-de82c22581b1', 'Солнце', '511dc56e-973e-487d-a423-0f2632893821', 'G2V', 1, 0.0000158, 5778),
('a9f9dc7f-e98f-47e1-ab18-4b2d33edd86c', 'Сириус', '511dc56e-973e-487d-a423-0f2632893821', 'A1V', 25.4, 8.6, 9940),
('c5d470dd-99f5-4019-951b-9623cb7027e4', 'Альфа Центавра A', '511dc56e-973e-487d-a423-0f2632893821', 'G2V', 1.519, 4.37, 5790),
('1351a026-c9db-46a1-9cf0-13727f631794', 'Арктур', '511dc56e-973e-487d-a423-0f2632893821', 'K0III', 170, 36.7, 4286),
('6ef914d5-48cd-4e9c-8093-4b4d6cefee57', 'Вега', '511dc56e-973e-487d-a423-0f2632893821', 'A0V', 40, 25, 9602);

INSERT INTO planet (id, name, mass, diameter, distance_from_star, surface_temperature, star_id)
VALUES
    ('b0d057f5-4a36-4d9c-8c7d-9f654c23bc91', 'Меркурий', 0.055, 4879, 57900000, 167, 'b3d784c1-1f31-475d-9059-de82c22581b1'),
    ('e9e4770e-2f0e-4d9f-8b14-61c892dca9a7', 'Венера', 0.815, 12104, 108000000, 464, 'b3d784c1-1f31-475d-9059-de82c22581b1'),
    ('49de8c5f-378a-4c9b-8973-1f1a93a0d801', 'Земля', 1, 12742, 149600000, 15, 'b3d784c1-1f31-475d-9059-de82c22581b1'),
    ('6ac22e86-86a3-47d4-8c29-3e2254be319e', 'Марс', 0.107, 6779, 227900000, -65, 'b3d784c1-1f31-475d-9059-de82c22581b1'),
    ('a10c8327-4d1f-47d1-91cd-52c95ff5808c', 'Юпитер', 317.8, 139822, 778300000, -145, 'b3d784c1-1f31-475d-9059-de82c22581b1'),
    ('6d0d8801-671a-47c4-8f6a-25a2f837b1a0', 'Сатурн', 95.2, 116464, 1427000000, -178, 'b3d784c1-1f31-475d-9059-de82c22581b1'),
    ('e1e0d00b-7e4e-4ce0-9329-8c4933b2ed53', 'Уран', 14.5, 50724, 2871000000, -224, 'b3d784c1-1f31-475d-9059-de82c22581b1'),
    ('eef995a6-8640-4da0-9e12-d3ecf7a564ed', 'Нептун', 17.1, 49244, 4497000000, -214, 'b3d784c1-1f31-475d-9059-de82c22581b1')
"""
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
